# .github/workflows/update-roster.yml
name: Update Roster

on:
  workflow_dispatch:
    inputs:
      username:
        description: "PDC Username"
        required: true
      password:
        description: "PDC Password"
        required: true
  schedule:
    - cron: "0 0 * * *" # 매일 00:00 UTC 실행 (한국시간 오전 9시)

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
