name: Update Roster

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - run: npm install

      - name: Run roster.js
        env:
          INPUT_PDC_USERNAME: ${{ secrets.PDC_USERNAME }}
          INPUT_PDC_PASSWORD: ${{ secrets.PDC_PASSWORD }}
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
          INPUT_FIREBASE_UID: ${{ secrets.FLUTTERFLOW_UID }}         # userId
          INPUT_ADMIN_FIREBASE_UID: ${{ secrets.FIREBASE_ADMIN_UID }} # adminId
        run: node -r dotenv/config roster.js

      - run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add public/roster.json public/roster.csv
          git commit -m "Update roster data" || echo "No changes to commit"
          git push
