name: Update Roster

on:
  workflow_dispatch:   # 수동 실행 버튼
    inputs:
      username:
        description: "PDC Username"
        required: true
      password:
        description: "PDC Password"
        required: true
  schedule:
    - cron: "0 0 * * *"   # 매일 00:00 UTC 실행 (한국시간 오전 9시)

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install   # ✅ npm ci → npm install 로 변경

      - name: Run roster.js
        env:
          PDC_USERNAME: ${{ github.event.inputs.username }}
          PDC_PASSWORD: ${{ github.event.inputs.password }}
        run: node roster.js

      - name: Commit and Push roster.json & roster.csv
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add roster.json roster.csv
          git commit -m "🔄 Auto-update roster files" || echo "No changes to commit"
          git push
